#!/bin/bash
curl -s "http://dictionary.reference.com/browse/$1" |
tr '\n' ' '|
sed 's/<\/div/@/g'|
tr @ '\n'|
grep '<div class="def-set"'|
sed 's/<[^b][^>]*>//g'|
sed 's/\(\(.\)\{80\}[^ ]*\)/\1@/g'|
sed 's/\(      [^ ]*\)/\1@/g'|
\tr @ '\n';
exit 0;
